package com.onlineshoppingsystem.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.onlineshoppingsystem.dataobject.ProductDO;

public interface ProductDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
	List<ProductDO> listProduct();
	
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    int insert(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    int insertSelective(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    ProductDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    int updateByPrimaryKeySelective(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    int updateByPrimaryKey(ProductDO record);
    
    int increaseSales(@Param("id")Integer id, @Param("amount")Integer amount);
}