package com.onlineshoppingsystem.dao;

import org.apache.ibatis.annotations.Param;

import com.onlineshoppingsystem.dataobject.ProductStockDO;

public interface ProductStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    int insert(ProductStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    int insertSelective(ProductStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    ProductStockDO selectByPrimaryKey(Integer id);
    
    ProductStockDO selectByProductId(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    int updateByPrimaryKeySelective(ProductStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    int updateByPrimaryKey(ProductStockDO record);
    
    int decreaseStock(@Param("productId")Integer productId, @Param("amount")Integer amount);
}