package com.onlineshoppingsystem.dataobject;

public class ProductDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.title
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.description
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.price
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.sales
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.img_url
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.id
     *
     * @return the value of product_info.id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.id
     *
     * @param id the value for product_info.id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.title
     *
     * @return the value of product_info.title
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.title
     *
     * @param title the value for product_info.title
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.description
     *
     * @return the value of product_info.description
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.description
     *
     * @param description the value for product_info.description
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.price
     *
     * @return the value of product_info.price
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.price
     *
     * @param price the value for product_info.price
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.sales
     *
     * @return the value of product_info.sales
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.sales
     *
     * @param sales the value for product_info.sales
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.img_url
     *
     * @return the value of product_info.img_url
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.img_url
     *
     * @param imgUrl the value for product_info.img_url
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}