package com.onlineshoppingsystem.dataobject;

import java.util.Date;

public class PromoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.promo_name
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private String promoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.start_date
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.end_date
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.product_id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.promo_product_price
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private Double promoProductPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.id
     *
     * @return the value of promo_info.id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.id
     *
     * @param id the value for promo_info.id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.promo_name
     *
     * @return the value of promo_info.promo_name
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public String getPromoName() {
        return promoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.promo_name
     *
     * @param promoName the value for promo_info.promo_name
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setPromoName(String promoName) {
        this.promoName = promoName == null ? null : promoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.start_date
     *
     * @return the value of promo_info.start_date
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.start_date
     *
     * @param startDate the value for promo_info.start_date
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.end_date
     *
     * @return the value of promo_info.end_date
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.end_date
     *
     * @param endDate the value for promo_info.end_date
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.product_id
     *
     * @return the value of promo_info.product_id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.product_id
     *
     * @param productId the value for promo_info.product_id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.promo_product_price
     *
     * @return the value of promo_info.promo_product_price
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public Double getPromoProductPrice() {
        return promoProductPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.promo_product_price
     *
     * @param promoProductPrice the value for promo_info.promo_product_price
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setPromoProductPrice(Double promoProductPrice) {
        this.promoProductPrice = promoProductPrice;
    }
}