package com.onlineshoppingsystem.dataobject;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.username
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.firstname
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.lastname
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.city
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.state
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.zip
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    private String zip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.username
     *
     * @return the value of user_info.username
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.username
     *
     * @param username the value for user_info.username
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.firstname
     *
     * @return the value of user_info.firstname
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.firstname
     *
     * @param firstname the value for user_info.firstname
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.lastname
     *
     * @return the value of user_info.lastname
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.lastname
     *
     * @param lastname the value for user_info.lastname
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.city
     *
     * @return the value of user_info.city
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.city
     *
     * @param city the value for user_info.city
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.state
     *
     * @return the value of user_info.state
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.state
     *
     * @param state the value for user_info.state
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.zip
     *
     * @return the value of user_info.zip
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.zip
     *
     * @param zip the value for user_info.zip
     *
     * @mbg.generated Mon Sep 21 19:10:20 CDT 2020
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }
}